apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    {{- include "hello-java.labels" . | nindent 4 }}
  name: {{ include "hello-java.fullname" . }}
spec:
  output:
    to:
      kind: DockerImage
      name: {{ .Values.build.target }}
  source:
    # Expect a local directory to be streamed to OpenShift as the build source
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      # The path in the source where the Dockerfile is located
      dockerfilePath: Dockerfile
